name: check norminette v3
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    name: norminette
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: 'philo/ philo_bonus/'
